//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.02 at 05:32:18 PM GMT-03:00 
//
package xml.topologyclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for colun element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="colun">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}hop"/>
 *           &lt;element ref="{}lenghtString" minOccurs="0"/>
 *           &lt;element ref="{}bit" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="family" use="required">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Base"/>
 *               &lt;enumeration value="MultiStage"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="type" use="required">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="HOP"/>
 *               &lt;enumeration value="InversePerfectShuffler"/>
 *               &lt;enumeration value="PerfectShuffler"/>
 *               &lt;enumeration value="BitReverse"/>
 *               &lt;enumeration value="Butterfly"/>
 *               &lt;enumeration value="BaseLine"/>
 *               &lt;enumeration value="Cube"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hop",
    "lenghtString",
    "bit"
})
@XmlRootElement(name = "colun")
public class Colun {

    protected int hop;
    protected Integer lenghtString;
    protected Integer bit;
    @XmlAttribute(required = true)
    protected String family;
    @XmlAttribute(required = true)
    protected String type;

    /**
     * Gets the value of the hop property.
     * 
     */
    public int getHop() {
        return hop;
    }

    /**
     * Sets the value of the hop property.
     * 
     */
    public void setHop(int value) {
        this.hop = value;
    }

    /**
     * Gets the value of the lenghtString property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLenghtString() {
        return lenghtString;
    }

    /**
     * Sets the value of the lenghtString property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLenghtString(Integer value) {
        this.lenghtString = value;
    }

    /**
     * Gets the value of the bit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBit() {
        return bit;
    }

    /**
     * Sets the value of the bit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBit(Integer value) {
        this.bit = value;
    }

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }
}
