//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}maxIterations"/>
 *         &lt;element ref="{}initialTemp"/>
 *         &lt;element ref="{}finalTemp"/>
 *         &lt;element ref="{}formulas"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Simulated Annealing" />
 *       &lt;attribute name="acronym" type="{http://www.w3.org/2001/XMLSchema}string" fixed="SA" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxIterations",
    "initialTemp",
    "finalTemp",
    "formulas"
})
@XmlRootElement(name = "annealing")
public class Annealing {

    @XmlElement(required = true)
    protected MaxIterations maxIterations;
    @XmlElement(required = true)
    protected InitialTemp initialTemp;
    @XmlElement(required = true)
    protected FinalTemp finalTemp;
    @XmlElement(required = true)
    protected Formulas formulas;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String acronym;

    /**
     * Gets the value of the maxIterations property.
     * 
     * @return
     *     possible object is
     *     {@link MaxIterations }
     *     
     */
    public MaxIterations getMaxIterations() {
        return maxIterations;
    }

    /**
     * Sets the value of the maxIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxIterations }
     *     
     */
    public void setMaxIterations(MaxIterations value) {
        this.maxIterations = value;
    }

    /**
     * Gets the value of the initialTemp property.
     * 
     * @return
     *     possible object is
     *     {@link InitialTemp }
     *     
     */
    public InitialTemp getInitialTemp() {
        return initialTemp;
    }

    /**
     * Sets the value of the initialTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialTemp }
     *     
     */
    public void setInitialTemp(InitialTemp value) {
        this.initialTemp = value;
    }

    /**
     * Gets the value of the finalTemp property.
     * 
     * @return
     *     possible object is
     *     {@link FinalTemp }
     *     
     */
    public FinalTemp getFinalTemp() {
        return finalTemp;
    }

    /**
     * Sets the value of the finalTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinalTemp }
     *     
     */
    public void setFinalTemp(FinalTemp value) {
        this.finalTemp = value;
    }

    /**
     * Gets the value of the formulas property.
     * 
     * @return
     *     possible object is
     *     {@link Formulas }
     *     
     */
    public Formulas getFormulas() {
        return formulas;
    }

    /**
     * Sets the value of the formulas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formulas }
     *     
     */
    public void setFormulas(Formulas value) {
        this.formulas = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Simulated Annealing";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcronym() {
        if (acronym == null) {
            return "SA";
        } else {
            return acronym;
        }
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcronym(String value) {
        this.acronym = value;
    }

}
