//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}typeCross"/>
 *         &lt;element ref="{}fileFix"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeCross",
    "fileFix"
})
@XmlRootElement(name = "fix")
public class Fix {

    @XmlElement(required = true)
    protected TypeCross typeCross;
    @XmlElement(required = true)
    protected FileFix fileFix;

    /**
     * Gets the value of the typeCross property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCross }
     *     
     */
    public TypeCross getTypeCross() {
        return typeCross;
    }

    /**
     * Sets the value of the typeCross property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCross }
     *     
     */
    public void setTypeCross(TypeCross value) {
        this.typeCross = value;
    }

    /**
     * Gets the value of the fileFix property.
     * 
     * @return
     *     possible object is
     *     {@link FileFix }
     *     
     */
    public FileFix getFileFix() {
        return fileFix;
    }

    /**
     * Sets the value of the fileFix property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileFix }
     *     
     */
    public void setFileFix(FileFix value) {
        this.fileFix = value;
    }

}
