//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}timeGeneration"/>
 *         &lt;element ref="{}numberGeneration"/>
 *         &lt;element ref="{}formatCross"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Genetic Algorithm" />
 *       &lt;attribute name="acronym" type="{http://www.w3.org/2001/XMLSchema}string" fixed="GA" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeGeneration",
    "numberGeneration",
    "formatCross"
})
@XmlRootElement(name = "genetic")
public class Genetic {

    @XmlElement(required = true)
    protected TimeGeneration timeGeneration;
    @XmlElement(required = true)
    protected NumberGeneration numberGeneration;
    @XmlElement(required = true)
    protected FormatCross formatCross;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String acronym;

    /**
     * Gets the value of the timeGeneration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeGeneration }
     *     
     */
    public TimeGeneration getTimeGeneration() {
        return timeGeneration;
    }

    /**
     * Sets the value of the timeGeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeGeneration }
     *     
     */
    public void setTimeGeneration(TimeGeneration value) {
        this.timeGeneration = value;
    }

    /**
     * Gets the value of the numberGeneration property.
     * 
     * @return
     *     possible object is
     *     {@link NumberGeneration }
     *     
     */
    public NumberGeneration getNumberGeneration() {
        return numberGeneration;
    }

    /**
     * Sets the value of the numberGeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberGeneration }
     *     
     */
    public void setNumberGeneration(NumberGeneration value) {
        this.numberGeneration = value;
    }

    /**
     * Gets the value of the formatCross property.
     * 
     * @return
     *     possible object is
     *     {@link FormatCross }
     *     
     */
    public FormatCross getFormatCross() {
        return formatCross;
    }

    /**
     * Sets the value of the formatCross property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatCross }
     *     
     */
    public void setFormatCross(FormatCross value) {
        this.formatCross = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Genetic Algorithm";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcronym() {
        if (acronym == null) {
            return "GA";
        } else {
            return acronym;
        }
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcronym(String value) {
        this.acronym = value;
    }

}
