//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}genetic"/>
 *         &lt;element ref="{}relinking"/>
 *         &lt;element ref="{}annealing"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "genetic",
    "relinking",
    "annealing"
})
@XmlRootElement(name = "heuristics")
public class Heuristics {

    @XmlElement(required = true)
    protected Genetic genetic;
    @XmlElement(required = true)
    protected Relinking relinking;
    @XmlElement(required = true)
    protected Annealing annealing;

    /**
     * Gets the value of the genetic property.
     * 
     * @return
     *     possible object is
     *     {@link Genetic }
     *     
     */
    public Genetic getGenetic() {
        return genetic;
    }

    /**
     * Sets the value of the genetic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genetic }
     *     
     */
    public void setGenetic(Genetic value) {
        this.genetic = value;
    }

    /**
     * Gets the value of the relinking property.
     * 
     * @return
     *     possible object is
     *     {@link Relinking }
     *     
     */
    public Relinking getRelinking() {
        return relinking;
    }

    /**
     * Sets the value of the relinking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Relinking }
     *     
     */
    public void setRelinking(Relinking value) {
        this.relinking = value;
    }

    /**
     * Gets the value of the annealing property.
     * 
     * @return
     *     possible object is
     *     {@link Annealing }
     *     
     */
    public Annealing getAnnealing() {
        return annealing;
    }

    /**
     * Sets the value of the annealing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annealing }
     *     
     */
    public void setAnnealing(Annealing value) {
        this.annealing = value;
    }

}
