//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Annealing }
     * 
     */
    public Annealing createAnnealing() {
        return new Annealing();
    }

    /**
     * Create an instance of {@link FileFix }
     * 
     */
    public FileFix createFileFix() {
        return new FileFix();
    }

    /**
     * Create an instance of {@link TimeGeneration }
     * 
     */
    public TimeGeneration createTimeGeneration() {
        return new TimeGeneration();
    }

    /**
     * Create an instance of {@link BasicParameters }
     * 
     */
    public BasicParameters createBasicParameters() {
        return new BasicParameters();
    }

    /**
     * Create an instance of {@link AllElements }
     * 
     */
    public AllElements createAllElements() {
        return new AllElements();
    }

    /**
     * Create an instance of {@link FirstElements }
     * 
     */
    public FirstElements createFirstElements() {
        return new FirstElements();
    }

    /**
     * Create an instance of {@link Repository }
     * 
     */
    public Repository createRepository() {
        return new Repository();
    }

    /**
     * Create an instance of {@link NumberGeneration }
     * 
     */
    public NumberGeneration createNumberGeneration() {
        return new NumberGeneration();
    }

    /**
     * Create an instance of {@link MaxIterations }
     * 
     */
    public MaxIterations createMaxIterations() {
        return new MaxIterations();
    }

    /**
     * Create an instance of {@link Genetic }
     * 
     */
    public Genetic createGenetic() {
        return new Genetic();
    }

    /**
     * Create an instance of {@link InitialTemp }
     * 
     */
    public InitialTemp createInitialTemp() {
        return new InitialTemp();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link TypeCost }
     * 
     */
    public TypeCost createTypeCost() {
        return new TypeCost();
    }

    /**
     * Create an instance of {@link TypeCross }
     * 
     */
    public TypeCross createTypeCross() {
        return new TypeCross();
    }

    /**
     * Create an instance of {@link PlacementVariation }
     * 
     */
    public PlacementVariation createPlacementVariation() {
        return new PlacementVariation();
    }

    /**
     * Create an instance of {@link ValueCost }
     * 
     */
    public ValueCost createValueCost() {
        return new ValueCost();
    }

    /**
     * Create an instance of {@link UpLimit }
     * 
     */
    public UpLimit createUpLimit() {
        return new UpLimit();
    }

    /**
     * Create an instance of {@link Formula1 }
     * 
     */
    public Formula1 createFormula1() {
        return new Formula1();
    }

    /**
     * Create an instance of {@link Heuristics }
     * 
     */
    public Heuristics createHeuristics() {
        return new Heuristics();
    }

    /**
     * Create an instance of {@link Orientation }
     * 
     */
    public Orientation createOrientation() {
        return new Orientation();
    }

    /**
     * Create an instance of {@link FileForStatistic }
     * 
     */
    public FileForStatistic createFileForStatistic() {
        return new FileForStatistic();
    }

    /**
     * Create an instance of {@link PlacementTime }
     * 
     */
    public PlacementTime createPlacementTime() {
        return new PlacementTime();
    }

    /**
     * Create an instance of {@link Formulas }
     * 
     */
    public Formulas createFormulas() {
        return new Formulas();
    }

    /**
     * Create an instance of {@link Fix }
     * 
     */
    public Fix createFix() {
        return new Fix();
    }

    /**
     * Create an instance of {@link Formula4 }
     * 
     */
    public Formula4 createFormula4() {
        return new Formula4();
    }

    /**
     * Create an instance of {@link Formula3 }
     * 
     */
    public Formula3 createFormula3() {
        return new Formula3();
    }

    /**
     * Create an instance of {@link RandomicElements }
     * 
     */
    public RandomicElements createRandomicElements() {
        return new RandomicElements();
    }

    /**
     * Create an instance of {@link AlgorithmRouting }
     * 
     */
    public AlgorithmRouting createAlgorithmRouting() {
        return new AlgorithmRouting();
    }

    /**
     * Create an instance of {@link DownLimit }
     * 
     */
    public DownLimit createDownLimit() {
        return new DownLimit();
    }

    /**
     * Create an instance of {@link FormatCross }
     * 
     */
    public FormatCross createFormatCross() {
        return new FormatCross();
    }

    /**
     * Create an instance of {@link FinalTemp }
     * 
     */
    public FinalTemp createFinalTemp() {
        return new FinalTemp();
    }

    /**
     * Create an instance of {@link Formula2 }
     * 
     */
    public Formula2 createFormula2() {
        return new Formula2();
    }

    /**
     * Create an instance of {@link Cost }
     * 
     */
    public Cost createCost() {
        return new Cost();
    }

    /**
     * Create an instance of {@link Relinking }
     * 
     */
    public Relinking createRelinking() {
        return new Relinking();
    }

    /**
     * Create an instance of {@link Taxa }
     * 
     */
    public Taxa createTaxa() {
        return new Taxa();
    }

    /**
     * Create an instance of {@link FormatCalc }
     * 
     */
    public FormatCalc createFormatCalc() {
        return new FormatCalc();
    }

    /**
     * Create an instance of {@link FileBench }
     * 
     */
    public FileBench createFileBench() {
        return new FileBench();
    }

    /**
     * Create an instance of {@link FilePopulation }
     * 
     */
    public FilePopulation createFilePopulation() {
        return new FilePopulation();
    }

    /**
     * Create an instance of {@link Elements }
     * 
     */
    public Elements createElements() {
        return new Elements();
    }

    /**
     * Create an instance of {@link PlacementPopulation }
     * 
     */
    public PlacementPopulation createPlacementPopulation() {
        return new PlacementPopulation();
    }

    /**
     * Create an instance of {@link Placement }
     * 
     */
    public Placement createPlacement() {
        return new Placement();
    }

    /**
     * Create an instance of {@link Toroide }
     * 
     */
    public Toroide createToroide() {
        return new Toroide();
    }

}
