//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}toroide"/>
 *         &lt;element ref="{}orientation"/>
 *         &lt;element ref="{}placementVariation"/>
 *         &lt;element ref="{}placementTime"/>
 *         &lt;element ref="{}filePopulation"/>
 *         &lt;element ref="{}placementPopulation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "toroide",
    "orientation",
    "placementVariation",
    "placementTime",
    "filePopulation",
    "placementPopulation"
})
@XmlRootElement(name = "placement")
public class Placement {

    @XmlElement(required = true)
    protected Toroide toroide;
    @XmlElement(required = true)
    protected Orientation orientation;
    @XmlElement(required = true)
    protected PlacementVariation placementVariation;
    @XmlElement(required = true)
    protected PlacementTime placementTime;
    @XmlElement(required = true)
    protected FilePopulation filePopulation;
    @XmlElement(required = true)
    protected PlacementPopulation placementPopulation;

    /**
     * Gets the value of the toroide property.
     * 
     * @return
     *     possible object is
     *     {@link Toroide }
     *     
     */
    public Toroide getToroide() {
        return toroide;
    }

    /**
     * Sets the value of the toroide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Toroide }
     *     
     */
    public void setToroide(Toroide value) {
        this.toroide = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link Orientation }
     *     
     */
    public Orientation getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Orientation }
     *     
     */
    public void setOrientation(Orientation value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the placementVariation property.
     * 
     * @return
     *     possible object is
     *     {@link PlacementVariation }
     *     
     */
    public PlacementVariation getPlacementVariation() {
        return placementVariation;
    }

    /**
     * Sets the value of the placementVariation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacementVariation }
     *     
     */
    public void setPlacementVariation(PlacementVariation value) {
        this.placementVariation = value;
    }

    /**
     * Gets the value of the placementTime property.
     * 
     * @return
     *     possible object is
     *     {@link PlacementTime }
     *     
     */
    public PlacementTime getPlacementTime() {
        return placementTime;
    }

    /**
     * Sets the value of the placementTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacementTime }
     *     
     */
    public void setPlacementTime(PlacementTime value) {
        this.placementTime = value;
    }

    /**
     * Gets the value of the filePopulation property.
     * 
     * @return
     *     possible object is
     *     {@link FilePopulation }
     *     
     */
    public FilePopulation getFilePopulation() {
        return filePopulation;
    }

    /**
     * Sets the value of the filePopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilePopulation }
     *     
     */
    public void setFilePopulation(FilePopulation value) {
        this.filePopulation = value;
    }

    /**
     * Gets the value of the placementPopulation property.
     * 
     * @return
     *     possible object is
     *     {@link PlacementPopulation }
     *     
     */
    public PlacementPopulation getPlacementPopulation() {
        return placementPopulation;
    }

    /**
     * Sets the value of the placementPopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacementPopulation }
     *     
     */
    public void setPlacementPopulation(PlacementPopulation value) {
        this.placementPopulation = value;
    }

}
