//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}allElements"/>
 *         &lt;element ref="{}firstElements"/>
 *         &lt;element ref="{}randomicElements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Path Relinking" />
 *       &lt;attribute name="acronym" type="{http://www.w3.org/2001/XMLSchema}string" fixed="PR" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allElements",
    "firstElements",
    "randomicElements"
})
@XmlRootElement(name = "relinking")
public class Relinking {

    @XmlElement(required = true)
    protected AllElements allElements;
    @XmlElement(required = true)
    protected FirstElements firstElements;
    @XmlElement(required = true)
    protected RandomicElements randomicElements;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String acronym;

    /**
     * Gets the value of the allElements property.
     * 
     * @return
     *     possible object is
     *     {@link AllElements }
     *     
     */
    public AllElements getAllElements() {
        return allElements;
    }

    /**
     * Sets the value of the allElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllElements }
     *     
     */
    public void setAllElements(AllElements value) {
        this.allElements = value;
    }

    /**
     * Gets the value of the firstElements property.
     * 
     * @return
     *     possible object is
     *     {@link FirstElements }
     *     
     */
    public FirstElements getFirstElements() {
        return firstElements;
    }

    /**
     * Sets the value of the firstElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirstElements }
     *     
     */
    public void setFirstElements(FirstElements value) {
        this.firstElements = value;
    }

    /**
     * Gets the value of the randomicElements property.
     * 
     * @return
     *     possible object is
     *     {@link RandomicElements }
     *     
     */
    public RandomicElements getRandomicElements() {
        return randomicElements;
    }

    /**
     * Sets the value of the randomicElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link RandomicElements }
     *     
     */
    public void setRandomicElements(RandomicElements value) {
        this.randomicElements = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Path Relinking";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcronym() {
        if (acronym == null) {
            return "PR";
        } else {
            return acronym;
        }
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcronym(String value) {
        this.acronym = value;
    }

}
