//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.25 at 02:38:57 PM GMT-03:00 
//


package xml.parametersclass;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}algorithmRouting"/>
 *         &lt;element ref="{}formatCalc"/>
 *         &lt;element ref="{}upLimit"/>
 *         &lt;element ref="{}downLimit"/>
 *         &lt;element ref="{}fileForStatistic"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "algorithmRouting",
    "formatCalc",
    "upLimit",
    "downLimit",
    "fileForStatistic"
})
@XmlRootElement(name = "route")
public class Route {

    @XmlElement(required = true)
    protected AlgorithmRouting algorithmRouting;
    @XmlElement(required = true)
    protected FormatCalc formatCalc;
    @XmlElement(required = true)
    protected UpLimit upLimit;
    @XmlElement(required = true)
    protected DownLimit downLimit;
    @XmlElement(required = true)
    protected FileForStatistic fileForStatistic;

    /**
     * Gets the value of the algorithmRouting property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmRouting }
     *     
     */
    public AlgorithmRouting getAlgorithmRouting() {
        return algorithmRouting;
    }

    /**
     * Sets the value of the algorithmRouting property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmRouting }
     *     
     */
    public void setAlgorithmRouting(AlgorithmRouting value) {
        this.algorithmRouting = value;
    }

    /**
     * Gets the value of the formatCalc property.
     * 
     * @return
     *     possible object is
     *     {@link FormatCalc }
     *     
     */
    public FormatCalc getFormatCalc() {
        return formatCalc;
    }

    /**
     * Sets the value of the formatCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatCalc }
     *     
     */
    public void setFormatCalc(FormatCalc value) {
        this.formatCalc = value;
    }

    /**
     * Gets the value of the upLimit property.
     * 
     * @return
     *     possible object is
     *     {@link UpLimit }
     *     
     */
    public UpLimit getUpLimit() {
        return upLimit;
    }

    /**
     * Sets the value of the upLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpLimit }
     *     
     */
    public void setUpLimit(UpLimit value) {
        this.upLimit = value;
    }

    /**
     * Gets the value of the downLimit property.
     * 
     * @return
     *     possible object is
     *     {@link DownLimit }
     *     
     */
    public DownLimit getDownLimit() {
        return downLimit;
    }

    /**
     * Sets the value of the downLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownLimit }
     *     
     */
    public void setDownLimit(DownLimit value) {
        this.downLimit = value;
    }

    /**
     * Gets the value of the fileForStatistic property.
     * 
     * @return
     *     possible object is
     *     {@link FileForStatistic }
     *     
     */
    public FileForStatistic getFileForStatistic() {
        return fileForStatistic;
    }

    /**
     * Sets the value of the fileForStatistic property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileForStatistic }
     *     
     */
    public void setFileForStatistic(FileForStatistic value) {
        this.fileForStatistic = value;
    }

}
